// Sample product data for demo (used when Supabase is not connected)

export const sampleProducts = [
  {
    id: '1',
    name: 'Classic Hot Sauce',
    slug: 'classic-hot-sauce',
    description: "Maa G's signature hot sauce made with hand-picked red chilies, roasted garlic, and a secret blend of spices passed down through three generations. This fiery condiment brings the perfect kick to any meal—from eggs to biryani, pizza to paratha. Every bottle is crafted in small batches to ensure maximum freshness and bold, authentic flavor.",
    short_description: 'Our signature fiery hot sauce with hand-picked red chilies and secret spices.',
    price: 450,
    compare_price: 550,
    category: 'Sauces',
    image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=600&auto=format&fit=crop', 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?q=80&w=600&auto=format&fit=crop'],
    spice_level: 4,
    is_featured: true,
    is_bestseller: true,
    in_stock: true,
    weight: '250ml',
    ingredients: 'Red Chilies, Garlic, Vinegar, Salt, Sugar, Spices',
  },
  {
    id: '2',
    name: 'Chili Garlic Sauce',
    slug: 'chili-garlic-sauce',
    description: "A bold fusion of crushed red chilies and roasted garlic, this sauce delivers a savory, spicy punch that's both versatile and addictive. Use it as a dipping sauce, a stir-fry base, or drizzle it over grilled meats and naan. Maa G uses a slow-cook method that lets the garlic caramelize beautifully with the chilies.",
    short_description: 'Bold crushed chilies with roasted garlic—perfect for dipping and cooking.',
    price: 400,
    compare_price: null,
    category: 'Sauces',
    image_url: 'https://images.unsplash.com/photo-1590213745265-27a3c3111da9?q=80&w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1590213745265-27a3c3111da9?q=80&w=600&auto=format&fit=crop', 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=600&auto=format&fit=crop'],
    spice_level: 3,
    is_featured: true,
    is_bestseller: false,
    in_stock: true,
    weight: '250ml',
    ingredients: 'Red Chilies, Garlic, Soybean Oil, Vinegar, Sugar, Salt',
  },
  {
    id: '3',
    name: 'Green Mint Chutney',
    slug: 'green-mint-chutney',
    description: "A refreshing blend of fresh mint, coriander, green chilies, and tangy lemon juice—this chutney is the perfect companion for samosas, pakoras, and kebabs. Maa G's recipe balances cool mint with just the right amount of heat, making it a must-have at every desi table.",
    short_description: 'Refreshing mint and coriander chutney—the perfect samosa companion.',
    price: 350,
    compare_price: 400,
    category: 'Chutneys',
    image_url: 'https://images.unsplash.com/photo-1627308595229-7830f5c9c66e?q=80&w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1627308595229-7830f5c9c66e?q=80&w=600&auto=format&fit=crop'],
    spice_level: 2,
    is_featured: true,
    is_bestseller: true,
    in_stock: true,
    weight: '200g',
    ingredients: 'Fresh Mint, Coriander, Green Chilies, Lemon Juice, Salt, Cumin',
  },
  {
    id: '4',
    name: 'Tamarind Date Chutney',
    slug: 'tamarind-date-chutney',
    description: "Sweet, tangy, and irresistibly delicious—our Tamarind Date Chutney is the heart of every chaat plate. Made with premium tamarind pulp, Khairpur dates, and a whisper of cumin and chili, this chutney strikes the perfect balance between sweet and sour. Drizzle it over fruit chaat, dahi baray, or papri chaat.",
    short_description: 'Sweet & tangy tamarind chutney—the soul of every chaat plate.',
    price: 350,
    compare_price: null,
    category: 'Chutneys',
    image_url: 'https://images.unsplash.com/photo-1589113103553-496dc6acb7e0?q=80&w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1589113103553-496dc6acb7e0?q=80&w=600&auto=format&fit=crop'],
    spice_level: 1,
    is_featured: false,
    is_bestseller: false,
    in_stock: true,
    weight: '250g',
    ingredients: 'Tamarind, Dates, Jaggery, Red Chili, Cumin, Salt',
  },
  {
    id: '5',
    name: 'Mango Pickle (Achaar)',
    slug: 'mango-pickle-achaar',
    description: "Bursting with the bold, tangy flavor of raw Sindhri mangoes, this traditional achaar is sun-ripened and hand-mixed with mustard oil, fenugreek, and fiery red chili powder. Maa G prepares every jar the old-fashioned way—left to mature in the sun for weeks until the flavors meld into perfection. An absolute essential for any Pakistani household.",
    short_description: 'Traditional sun-ripened mango achaar with mustard oil and fiery spices.',
    price: 500,
    compare_price: 600,
    category: 'Pickles',
    image_url: 'https://images.unsplash.com/photo-1606112219348-204d7d8b94ee?q=80&w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1606112219348-204d7d8b94ee?q=80&w=600&auto=format&fit=crop'],
    spice_level: 4,
    is_featured: true,
    is_bestseller: true,
    in_stock: true,
    weight: '400g',
    ingredients: 'Raw Mango, Mustard Oil, Red Chili Powder, Fenugreek Seeds, Fennel Seeds, Salt, Turmeric',
  },
  {
    id: '6',
    name: 'Mixed Vegetable Achaar',
    slug: 'mixed-vegetable-achaar',
    description: "A delightful medley of carrots, turnips, cauliflower, green chilies, and raw mango pieces—all drenched in tangy mustard oil and aromatic spices. This classic mixed pickle offers something for everyone: the crunch of fresh vegetables, the heat of red chilies, and the sourness of raw mango. A jar lasts all year long!",
    short_description: 'Classic mixed pickle with carrots, turnips, cauliflower, and raw mango.',
    price: 550,
    compare_price: null,
    category: 'Pickles',
    image_url: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=600&auto=format&fit=crop'],
    spice_level: 3,
    is_featured: false,
    is_bestseller: false,
    in_stock: true,
    weight: '450g',
    ingredients: 'Carrots, Turnips, Cauliflower, Green Chilies, Raw Mango, Mustard Oil, Spices, Salt',
  },
  {
    id: '7',
    name: 'Garam Masala',
    slug: 'garam-masala',
    description: "Freshly roasted and hand-ground, Maa G's Garam Masala is a fragrant blend of cinnamon, cardamom, cloves, black pepper, cumin, and bay leaves. Unlike store-bought blends, our masala is made in small batches—so every pinch delivers an explosion of warm, aromatic flavor to your curries, biryanis, and gravies.",
    short_description: 'Hand-roasted aromatic spice blend for curries, biryani, and gravies.',
    price: 300,
    compare_price: null,
    category: 'Masalas',
    image_url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=600&auto=format&fit=crop'],
    spice_level: 2,
    is_featured: true,
    is_bestseller: false,
    in_stock: true,
    weight: '100g',
    ingredients: 'Cinnamon, Cardamom, Cloves, Black Pepper, Cumin Seeds, Bay Leaves',
  },
  {
    id: '8',
    name: 'Biryani Masala',
    slug: 'biryani-masala',
    description: "The secret behind every unforgettable biryani. Maa G's Biryani Masala is a carefully curated blend of over 12 spices including fennel, mace, nutmeg, star anise, and saffron-infused spices. Just one tablespoon transforms ordinary rice and meat into a fragrant, restaurant-quality biryani. Perfect for Karachi, Lucknowi, and Hyderabadi styles.",
    short_description: 'The secret 12-spice blend for restaurant-quality biryani at home.',
    price: 350,
    compare_price: 420,
    category: 'Masalas',
    image_url: 'https://images.unsplash.com/photo-1505253149613-112d21d9f6a9?q=80&w=600&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1505253149613-112d21d9f6a9?q=80&w=600&auto=format&fit=crop'],
    spice_level: 3,
    is_featured: true,
    is_bestseller: true,
    in_stock: true,
    weight: '100g',
    ingredients: 'Cumin, Coriander, Fennel, Mace, Nutmeg, Star Anise, Cardamom, Cinnamon, Cloves, Black Pepper, Bay Leaves, Dried Rose Petals',
  },
];

export const sampleReviews = [
  {
    id: '1',
    product_id: '1',
    name: 'Ahmed Khan',
    rating: 5,
    comment: 'Best hot sauce I\'ve ever had! The spice level is perfect and it goes with everything. My whole family is obsessed!',
    created_at: '2026-03-15T10:00:00Z',
  },
  {
    id: '2',
    product_id: '5',
    name: 'Fatima Zahra',
    rating: 5,
    comment: 'This mango achaar reminds me of my grandmother\'s recipe. Authentic, tangy, and perfectly spiced. Will definitely order again!',
    created_at: '2026-03-12T14:30:00Z',
  },
  {
    id: '3',
    product_id: '3',
    name: 'Bilal Hussain',
    rating: 4,
    comment: 'The green chutney is so fresh and flavorful. Perfect with samosas and pakoras. A little goes a long way.',
    created_at: '2026-03-10T09:15:00Z',
  },
  {
    id: '4',
    product_id: '8',
    name: 'Ayesha Malik',
    rating: 5,
    comment: 'Made biryani with this masala and it turned out amazing! My husband thought I ordered from a restaurant 😂',
    created_at: '2026-02-28T16:45:00Z',
  },
  {
    id: '5',
    product_id: '2',
    name: 'Usman Ali',
    rating: 5,
    comment: 'Absolutely love the chili garlic sauce. Use it on everything—eggs, naan, rice. Pure fire! 🔥',
    created_at: '2026-02-20T11:00:00Z',
  },
  {
    id: '6',
    product_id: '7',
    name: 'Sana Rehman',
    rating: 4,
    comment: 'You can tell this garam masala is freshly ground. The aroma is incredible compared to supermarket brands.',
    created_at: '2026-02-15T18:20:00Z',
  },
];

export const categories = [
  { name: 'Sauces', slug: 'sauces', image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=400&auto=format&fit=crop', description: 'Hand-crafted hot & savory sauces', color: '#D32F2F' },
  { name: 'Chutneys', slug: 'chutneys', image: 'https://images.unsplash.com/photo-1627308595229-7830f5c9c66e?q=80&w=400&auto=format&fit=crop', description: 'Fresh & tangy traditional chutneys', color: '#4CAF50' },
  { name: 'Pickles', slug: 'pickles', image: 'https://images.unsplash.com/photo-1606112219348-204d7d8b94ee?q=80&w=400&auto=format&fit=crop', description: 'Sun-ripened traditional achaar', color: '#FF9800' },
  { name: 'Masalas', slug: 'masalas', image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=400&auto=format&fit=crop', description: 'Freshly ground spice blends', color: '#9C27B0' },
];

export const faqData = [
  {
    category: 'Ordering',
    questions: [
      { q: 'How do I place an order?', a: 'Simply browse our shop, add your favorite items to the cart, and proceed to checkout. You can pay via Cash on Delivery or online transfer.' },
      { q: 'Can I modify or cancel my order?', a: 'You can modify or cancel your order within 2 hours of placing it. After that, your order enters processing and cannot be changed. Contact us at hello@maagskitchen.pk for urgent changes.' },
      { q: 'Is there a minimum order requirement?', a: 'No minimum order! However, orders above Rs. 2,000 qualify for free shipping across Pakistan.' },
      { q: 'Do you offer bulk/wholesale orders?', a: 'Yes! We offer wholesale pricing for orders of 50+ units. Contact us directly for wholesale inquiries and custom packaging options.' },
    ],
  },
  {
    category: 'Shipping',
    questions: [
      { q: 'Where do you deliver?', a: 'We deliver nationwide across Pakistan. Major cities receive orders within 2-3 business days, while other areas may take 4-5 business days.' },
      { q: 'How much is shipping?', a: 'Shipping is Rs. 200 flat rate for orders under Rs. 2,000. Orders above Rs. 2,000 qualify for FREE shipping nationwide!' },
      { q: 'Can I track my order?', a: 'Yes! Once your order is dispatched, you will receive a tracking number via SMS and email that you can use to track your parcel.' },
      { q: 'Do you ship internationally?', a: "Currently, we only ship within Pakistan. International shipping is coming soon! Join our newsletter to be the first to know." },
    ],
  },
  {
    category: 'Products',
    questions: [
      { q: 'Are your products homemade?', a: "Yes, 100%! Every product is made by hand in Maa G's kitchen using traditional family recipes. We never use factory production or artificial preservatives." },
      { q: 'What is the shelf life of your products?', a: 'Our sauces last 3-4 months refrigerated, chutneys 2-3 weeks, pickles 6-12 months, and masalas 6 months when stored in airtight containers in a cool, dry place.' },
      { q: 'Are your products halal?', a: 'Absolutely! All our products are 100% halal and made with the highest quality, ethically sourced ingredients.' },
      { q: 'Do you use preservatives?', a: "No artificial preservatives. We use natural preservation methods—vinegar, salt, mustard oil, and traditional sun-drying techniques that have been used for generations." },
    ],
  },
  {
    category: 'Returns & Refunds',
    questions: [
      { q: 'What is your return policy?', a: "If you receive a damaged or incorrect product, we'll replace it or give a full refund. Contact us within 24 hours of delivery with photos of the issue." },
      { q: 'How do I request a refund?', a: 'Email us at hello@maagskitchen.pk with your order number and details. Refunds are processed within 3-5 business days.' },
      { q: 'Can I return a product I just don\'t like?', a: "Due to the perishable nature of our products, we can't accept returns for taste preference. However, we're happy to help you find products you'll love!" },
    ],
  },
];
