// Sample product data for demo (used when Supabase is not connected)

export const sampleProducts = [
  {
    id: '1',
    name: 'Red Chilli Sauce',
    slug: 'red-chilli-sauce',
    description: "Handcrafted Red Chilli Sauce. No added sugars, artificial flavors, thickeners, or stabilizers. This fiery condiment brings the perfect kick to any meal. Every bottle is crafted in small batches to ensure maximum freshness and bold, authentic flavor.",
    short_description: 'Our signature fiery hot sauce with hand-picked red chilies and secret spices.',
    price: 935,
    compare_price: null,
    category: 'Sauces',
    image_url: '/images/products/red-chilli.png',
    images: [
      '/images/products/red-chilli.png',
      'https://images.unsplash.com/photo-1596649282321-dfa56b6942da?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1588123190131-1c3fac394f4b?q=80&w=800&auto=format&fit=crop'
    ],
    spice_level: 4,
    is_featured: true,
    is_bestseller: true,
    in_stock: true,
    weight: '250ml',
    ingredients: 'Red Chilies, Garlic, Vinegar, Salt, Spices',
  },
  {
    id: '2',
    name: 'Green Chilli Sauce',
    slug: 'green-chilli-sauce',
    description: "A boldly refreshing fusion of crushed green chilies and select herbs. No added sugars, artificial flavors, thickeners, or stabilizers. It delivers a savory, spicy punch that's both versatile and addictive.",
    short_description: 'Fresh and vibrant green chilli sauce—perfect for dipping and cooking.',
    price: 850,
    compare_price: null,
    category: 'Sauces',
    image_url: '/images/products/green-chilli.png',
    images: [
      '/images/products/green-chilli.png',
      'https://images.unsplash.com/photo-1606883200984-c68e980a370e?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1596649282321-dfa56b6942da?q=80&w=800&auto=format&fit=crop'
    ],
    spice_level: 3,
    is_featured: true,
    is_bestseller: false,
    in_stock: true,
    weight: '250ml',
    ingredients: 'Green Chilies, Garlic, Vinegar, Salt, Herbs',
  },
  {
    id: '3',
    name: 'Garlic Mayo Sauce',
    slug: 'garlic-mayo-sauce',
    description: "Rich, creamy, and loaded with robust garlic flavor. Our hand-crafted Garlic Mayo is preservative free with no artificial thickeners. The perfect dip for fries, burgers, or a delicious sandwich spread.",
    short_description: 'Creamy artisanal mayo with a robust garlic kick.',
    price: 935,
    compare_price: null,
    category: 'Sauces',
    image_url: '/images/products/garlic-mayo.png',
    images: [
      '/images/products/garlic-mayo.png',
      'https://images.unsplash.com/photo-1589301773099-0a6d0be433eb?q=80&w=800&auto=format&fit=crop'
    ],
    spice_level: 1,
    is_featured: true,
    is_bestseller: true,
    in_stock: true,
    weight: '250ml',
    ingredients: 'Oil, Eggs, Garlic, Vinegar, Mustard, Salt',
  },
  {
    id: '4',
    name: 'Imli Aloo Bahara Sauce',
    slug: 'imli-aloo-bahara-sauce',
    description: "Sweet, tangy, and irresistibly delicious. Made with premium tamarind pulp and dried plums. No added sugars or artificial thickeners. This sauce strikes the perfect balance between sweet and sour.",
    short_description: 'Sweet & tangy tamarind and plum sauce—the soul of every chaat plate.',
    price: 800,
    compare_price: 950,
    category: 'Sauces',
    image_url: '/images/products/imli-aloo-bahara.png',
    images: [
      '/images/products/imli-aloo-bahara.png',
      'https://images.unsplash.com/photo-1628294895950-9ec87b4695e1?q=80&w=800&auto=format&fit=crop'
    ],
    spice_level: 1,
    is_featured: true,
    is_bestseller: true,
    in_stock: true,
    weight: '250ml',
    ingredients: 'Tamarind Pulp, Dried Plums, Traditional Spices',
  },
  {
    id: '5',
    name: 'Habanero Sauce',
    slug: 'habanero-sauce',
    description: "Small Batch. Made with fresh habanero peppers, vinegar, garlic, and special spices. Caution: Very Hot. Preservative Free. An absolute essential for heat seekers looking for intense flavor.",
    short_description: 'Intensely hot, small-batch artisanal Habanero sauce.',
    price: 1100,
    compare_price: null,
    category: 'Sauces',
    image_url: '/images/products/habanero.png',
    images: [
      '/images/products/habanero.png',
      'https://images.unsplash.com/photo-1596649282321-dfa56b6942da?q=80&w=800&auto=format&fit=crop'
    ],
    spice_level: 5,
    is_featured: true,
    is_bestseller: false,
    in_stock: true,
    weight: '250ml',
    ingredients: 'Habanero Peppers, Garlic, Vinegar, Special Spices',
  },
  {
    id: '6',
    name: 'Traditional Mango Pickle',
    slug: 'mango-pickle',
    description: "Authentic, sun-dried mango pickle cured for months to develop a deeply sour, spicy profile. Made just like Maa used to make it.",
    short_description: 'Authentic sun-dried mango pickle with traditional spices.',
    price: 750,
    compare_price: null,
    category: 'Pickles',
    image_url: 'https://images.unsplash.com/photo-1589301773099-0a6d0be433eb?q=80&w=800&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1589301773099-0a6d0be433eb?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1628294895950-9ec87b4695e1?q=80&w=800&auto=format&fit=crop'
    ],
    spice_level: 4,
    is_featured: true,
    is_bestseller: true,
    in_stock: true,
    weight: '400g',
    ingredients: 'Raw Mango, Mustard Oil, Fenugreek, Fennel, Red Chili',
  },
  {
    id: '7',
    name: 'Spicy Mixed Pickle',
    slug: 'mixed-pickle',
    description: "A medley of fresh seasonal vegetables including carrots, lemon, green chilies, and mangoes, marinated in our signature spice blend.",
    short_description: 'A punchy medley of seasonal vegetables and spices.',
    price: 800,
    compare_price: null,
    category: 'Pickles',
    image_url: 'https://images.unsplash.com/photo-1628294895950-9ec87b4695e1?q=80&w=800&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1628294895950-9ec87b4695e1?q=80&w=800&auto=format&fit=crop'
    ],
    spice_level: 3,
    is_featured: false,
    is_bestseller: false,
    in_stock: true,
    weight: '400g',
    ingredients: 'Carrot, Lemon, Mango, Chili, Spices, Mustard Oil',
  }
];

export const sampleReviews = [
  {
    id: '1',
    product_id: '1',
    name: 'Ahmed Khan',
    rating: 5,
    comment: 'Best hot sauce I\'ve ever had! The spice level is perfect and it goes with everything. My whole family is obsessed!',
    created_at: '2026-03-15T10:00:00Z',
  },
  {
    id: '2',
    product_id: '5',
    name: 'Fatima Zahra',
    rating: 5,
    comment: 'This mango achaar reminds me of my grandmother\'s recipe. Authentic, tangy, and perfectly spiced. Will definitely order again!',
    created_at: '2026-03-12T14:30:00Z',
  },
  {
    id: '3',
    product_id: '3',
    name: 'Bilal Hussain',
    rating: 4,
    comment: 'The green chutney is so fresh and flavorful. Perfect with samosas and pakoras. A little goes a long way.',
    created_at: '2026-03-10T09:15:00Z',
  },
  {
    id: '4',
    product_id: '8',
    name: 'Ayesha Malik',
    rating: 5,
    comment: 'Made biryani with this masala and it turned out amazing! My husband thought I ordered from a restaurant 😂',
    created_at: '2026-02-28T16:45:00Z',
  },
  {
    id: '5',
    product_id: '2',
    name: 'Usman Ali',
    rating: 5,
    comment: 'Absolutely love the chili garlic sauce. Use it on everything—eggs, naan, rice. Pure fire! 🔥',
    created_at: '2026-02-20T11:00:00Z',
  },
  {
    id: '6',
    product_id: '7',
    name: 'Sana Rehman',
    rating: 4,
    comment: 'You can tell this garam masala is freshly ground. The aroma is incredible compared to supermarket brands.',
    created_at: '2026-02-15T18:20:00Z',
  },
];
export const categories = [
  { name: 'Red Chilli Sauce',    slug: 'red-chilli-sauce',       image: '/images/products/red-chilli.png',       description: 'Handcrafted small-batch fiery sauce',   color: '#C0392B', bgColor: '#FFF0EE' },
  { name: 'Green Chilli Sauce',  slug: 'green-chilli-sauce',     image: '/images/products/green-chilli.png',     description: 'Fresh & herbaceous green chilli sauce', color: '#4CAF50', bgColor: '#F0F7EE' },
  { name: 'Garlic Mayo',         slug: 'garlic-mayo-sauce',      image: '/images/products/garlic-mayo.png',      description: 'Rich, creamy artisanal mayo',          color: '#B8860B', bgColor: '#FEFBF0' },
  { name: 'Imli Aloo Bahara',    slug: 'imli-aloo-bahara-sauce', image: '/images/products/imli-aloo-bahara.png', description: 'Sweet & tangy tamarind sauce',         color: '#7B3F00', bgColor: '#FBF3EE' },
  { name: 'Habanero Sauce',      slug: 'habanero-sauce',         image: '/images/products/habanero.png',         description: 'Small batch — serious heat',           color: '#FF5722', bgColor: '#FFF1EE' },
  { name: 'Authentic Pickles',   slug: 'pickles',                image: 'https://images.unsplash.com/photo-1589301773099-0a6d0be433eb?q=80&w=800&auto=format&fit=crop', description: 'Sun-cured traditional pickles',        color: '#E67E22', bgColor: '#FDF2E9' },
];

export const faqData = [
  {
    category: 'Ordering',
    questions: [
      { q: 'How do I place an order?', a: 'Simply browse our shop, add your favorite items to the cart, and proceed to checkout. You can pay via Cash on Delivery or online transfer.' },
      { q: 'Can I modify or cancel my order?', a: 'You can modify or cancel your order within 2 hours of placing it. After that, your order enters processing and cannot be changed. Contact us at hello@maagskitchen.pk for urgent changes.' },
      { q: 'Is there a minimum order requirement?', a: 'No minimum order! However, orders above Rs. 2,000 qualify for free shipping across Pakistan.' },
      { q: 'Do you offer bulk/wholesale orders?', a: 'Yes! We offer wholesale pricing for orders of 50+ units. Contact us directly for wholesale inquiries and custom packaging options.' },
    ],
  },
  {
    category: 'Shipping',
    questions: [
      { q: 'Where do you deliver?', a: 'We deliver nationwide across Pakistan. Major cities receive orders within 2-3 business days, while other areas may take 4-5 business days.' },
      { q: 'How much is shipping?', a: 'Shipping is Rs. 200 flat rate for orders under Rs. 2,000. Orders above Rs. 2,000 qualify for FREE shipping nationwide!' },
      { q: 'Can I track my order?', a: 'Yes! Once your order is dispatched, you will receive a tracking number via SMS and email that you can use to track your parcel.' },
      { q: 'Do you ship internationally?', a: "Currently, we only ship within Pakistan. International shipping is coming soon! Join our newsletter to be the first to know." },
    ],
  },
  {
    category: 'Products',
    questions: [
      { q: 'Are your products homemade?', a: "Yes, 100%! Every product is made by hand in Maa G's kitchen using traditional family recipes. We never use factory production or artificial preservatives." },
      { q: 'What is the shelf life of your products?', a: 'Our sauces last 3-4 months refrigerated, chutneys 2-3 weeks, pickles 6-12 months, and masalas 6 months when stored in airtight containers in a cool, dry place.' },
      { q: 'Are your products halal?', a: 'Absolutely! All our products are 100% halal and made with the highest quality, ethically sourced ingredients.' },
      { q: 'Do you use preservatives?', a: "No artificial preservatives. We use natural preservation methods—vinegar, salt, mustard oil, and traditional sun-drying techniques that have been used for generations." },
    ],
  },
  {
    category: 'Returns & Refunds',
    questions: [
      { q: 'What is your return policy?', a: "If you receive a damaged or incorrect product, we'll replace it or give a full refund. Contact us within 24 hours of delivery with photos of the issue." },
      { q: 'How do I request a refund?', a: 'Email us at hello@maagskitchen.pk with your order number and details. Refunds are processed within 3-5 business days.' },
      { q: 'Can I return a product I just don\'t like?', a: "Due to the perishable nature of our products, we can't accept returns for taste preference. However, we're happy to help you find products you'll love!" },
    ],
  },
];
